services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=my_user
      - MONGO_INITDB_ROOT_PASSWORD=my_pass
      - MONGO_INITDB_DATABASE=my_mongo_db
    ports:
      - "27017:27017"
    networks:
      - backend

  flask:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
